"""
Constants for LMS integration.

:copyright: (c) 2025-2026 by Meir Miyara.
:license: MPL-2.0, see LICENSE for more details.
"""

POLL_INTERVAL = 3
WATCHDOG_INTERVAL = 30
RECONNECT_DELAY = 10
CONNECT_TIMEOUT = 10
REQUEST_TIMEOUT = 10
CONNECT_RETRIES = 3
CONNECT_RETRY_DELAY = 3
MAX_POLL_FAILURES = 5
MAX_FAVOURITE_COMMANDS = 20
PAGE_SIZE = 50

DEFAULT_PORT = 9000
